sylius_ui:
  events:
    sylius.shop.layout.javascripts:
      blocks:
        bitbag_inpost_scripts:
          template: "@BitBagSyliusInPostPlugin/Shop/_scripts.html.twig"
          priority: 0
    sylius.shop.layout.stylesheets:
      blocks:
        bitbag_inpost_styles:
          template: "@BitBagSyliusInPostPlugin/Shop/_styles.html.twig"
          priority: 0
    sylius.shop.checkout.select_shipping.before_form:
        blocks:
          bitbag_inpost_scripts:
            template: "@BitBagSyliusInPostPlugin/InPostGeowidgetAssets.html.twig"
            priority: 0
    sylius.admin.layout.javascripts:
      blocks:
        bitbag_inpost_scripts:
          template: "@BitBagSyliusInPostPlugin/Admin/_scripts.html.twig"
          priority: 0
    sylius.admin.layout.stylesheets:
      blocks:
        bitbag_inpost_styles:
          template: "@BitBagSyliusInPostPlugin/Admin/_styles.html.twig"
          priority: 0
    sylius.admin.order.show.sidebar:
      blocks:
        bitbag_inpost_scripts:
          template: "@BitBagSyliusInPostPlugin/InPostGeowidgetAssets.html.twig"
          priority: 60